'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { usePathname} from 'next/navigation'
import { Providers } from './GlobalRedux/provider';
import { AuthContextProvider } from './context/AuthContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const navigation = [
    { name: "Główna", href: "/", current: true },
    { name: "Wydatek", href: "/wydatek", current: false },
    { name: "Login", href: "/signin", current: false },
  ];
 
  return (
    <html lang="pl">
      <body className={inter.className}>
        <div className='h-[92px] flex justify-center items-center '>
          {navigation.map((item) => (
          <Link
            href={{
              pathname: `${item.href}`,
              // query: { state: true },
            }}
            key={item.name}           
            className={
              pathname === item.href
                ? " text-zielony-1 outline-none text-xl   font-semibold  mr-4 "
                : "text-textMenu outline-none  text-xl         transition  duration-500 cursor-pointer mr-4   font-semibold "
            }
          >
            {item.name.toUpperCase()}
          </Link>
        ))}
        </div>
        <div className='h-[calc(100vh_-_92px)]'>
          <Providers>
            <AuthContextProvider>
            {children}
            </AuthContextProvider>
          </Providers>
        </div>      
        </body>
    </html>
  )
}
